name: Build and Deploy Next.js to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Next.js Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-cicd-example:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Checkout Kubernetes Manifests Repository
        uses: actions/checkout@v4
        with:
          repository: HoJin9622/nextjs-cicd-example-k8s # YOUR_GITHUB_USERNAME 변경
          path: nextjs-cicd-example-k8s # Clone into a new directory
          token: ${{ secrets.K8S_REPO_TOKEN }}

      - name: Update Kubernetes Deployment Image
        run: |
          cd nextjs-cicd-example-k8s/k8s
          # sed를 사용하여 deployment.yaml 파일의 이미지 태그를 업데이트합니다.
          # YOUR_DOCKER_USERNAME 부분도 실제 사용자 이름으로 변경해야 합니다.
          sed -i "s|image: your_docker_username/nextjs-cicd-example:.*|image: ${{ secrets.DOCKER_USERNAME }}/nextjs-cicd-example:${{ github.sha }}|" deployment.yaml
          cat deployment.yaml # 변경된 내용 확인
        env:
          YOUR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # GitHub Actions 환경 변수로 전달

      - name: Commit and Push Kubernetes Manifest Changes
        run: |
          cd nextjs-cicd-example-k8s
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add k8s/deployment.yaml
          git commit -m "Update nextjs-app image to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
        env:
          K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }} # 필요한 경우 env로 토큰 전달
